import { customer } from "../app/data";
import { C } from "../app/theme";
import { AgentBlock, Card, CardPad, ConfidenceBar, Header, PrimaryBtn, Row, SectionTitle, Tag, StatusPill, DangerBtn, SecondaryBtn } from "../app/ui";

export default function CSPage() {
  const cr = customer.contactReadiness;
  const ro = customer.recommendedOutreach;
  const approvalMaterials = [
    { agent: "CS Agent", title: "触达限制判断", summary: "本轮外呼仅建议通过已授权主联系人触达，不可直接联系配偶，也不可提前给出口头优惠承诺。", time: "今天 15:35" },
    { agent: "CS Agent", title: "回访建议草稿", summary: "建议用服务与体验补充切入，确认客户是否愿意安排家庭体验窗口。", time: "今天 15:38" },
    { agent: "Customer Agent", title: "状态候选更新", summary: "客户进入需要服务协同的家庭决策阶段，当前应先稳住关系温度，再补齐关键验证信息。", time: "今天 15:40" },
  ] as const;
  return (
    <div>
      <Header page="cs" />
      <div style={{ background: C.amberLight, borderBottom: `1px solid ${C.amberBorder}`, padding: "10px 28px" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto", display: "flex", gap: 16, alignItems: "center", flexWrap: "wrap" }}><span style={{ fontSize: 13, color: "#92400E", fontWeight: 500 }}>⚠ 本次外呼需遵守授权边界。直接联系配偶及承诺折扣均受限，需升级审批。</span><Tag label="需要审核" variant="amber" small /></div>
      </div>
      <div className="split-grid" style={{ display: "grid", gridTemplateColumns: "3fr 2fr", gap: 24, maxWidth: 1200, margin: "24px auto", padding: "0 28px" }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <Card style={{ borderColor: C.amberBorder }}><CardPad><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, flexWrap: "wrap", marginBottom: 12 }}><div><SectionTitle>待审批详情</SectionTitle><div style={{ fontSize: 13, color: C.text2 }}>默认展示 CS Agent 与 Customer Agent 的材料，用于你完成本次审批。</div></div><Tag label="客服视角" variant="amber" small /></div><div style={{ display: "grid", gap: 10, marginBottom: 14 }}>{approvalMaterials.map((item) => <div key={`${item.agent}-${item.title}`} style={{ background: C.surfaceAlt, border: `1px solid ${C.border}`, borderRadius: 10, padding: "12px 14px" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 8, flexWrap: "wrap" }}><div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}><Tag label={item.agent} variant={item.agent === "CS Agent" ? "blue" : "neutral"} small /><span style={{ fontSize: 14, fontWeight: 700, color: C.text0 }}>{item.title}</span></div><span style={{ fontSize: 12, color: C.text2 }}>{item.time}</span></div><div style={{ fontSize: 13, color: C.text1, lineHeight: 1.7 }}>{item.summary}</div></div>)}</div><div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}><PrimaryBtn style={{ minWidth: 106 }}>审批</PrimaryBtn><SecondaryBtn style={{ minWidth: 180 }}>修改后提交</SecondaryBtn><DangerBtn style={{ minWidth: 106 }}>驳回</DangerBtn></div></CardPad></Card>
          <div style={{ fontSize: 11, fontWeight: 600, color: C.text2, letterSpacing: 0.8, textTransform: "uppercase" }}>触达准备度</div>
          <Card style={{ borderColor: C.greenBorder }}><CardPad style={{ paddingBottom: 8 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}><SectionTitle>允许动作</SectionTitle><Tag label={`允许 ${cr.allowed.length} 项`} variant="green" small /></div>{cr.allowed.map((action, index) => <Row key={action} last={index === cr.allowed.length - 1}><span style={{ color: C.green, fontWeight: 700 }}>✓</span><span style={{ fontSize: 13, color: C.text0 }}>{action}</span></Row>)}</CardPad></Card>
          <Card style={{ borderColor: C.redBorder }}><CardPad style={{ paddingBottom: 8 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}><SectionTitle>受限动作</SectionTitle><Tag label={`受限 ${cr.blocked.length} 项`} variant="red" small /></div>{cr.blocked.map((action, index) => <Row key={action} last={index === cr.blocked.length - 1}><span style={{ color: C.red, fontWeight: 700 }}>✕</span><span style={{ fontSize: 13, color: C.text1 }}>{action}</span></Row>)}<div style={{ marginTop: 12, background: C.redLight, borderRadius: 7, padding: "9px 12px", fontSize: 12, color: C.red }}>限制来源：授权边界 / 合规策略 / 审批流程。如需突破，提交升级申请。</div></CardPad></Card>
          <div className="mini-grid" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}><Card><CardPad><SectionTitle>优先渠道</SectionTitle><div style={{ display: "flex", gap: 10, alignItems: "center" }}><span style={{ fontSize: 22 }}>💬</span><div><div style={{ fontSize: 14, fontWeight: 600, color: C.text0 }}>{cr.channel}</div><div style={{ fontSize: 11.5, color: C.text2 }}>{cr.channelNote}</div></div></div></CardPad></Card><Card><CardPad><SectionTitle>关系温度</SectionTitle><div style={{ display: "flex", alignItems: "center", gap: 8 }}><div style={{ flex: 1, height: 6, background: C.surfaceAlt, borderRadius: 3, overflow: "hidden", border: `1px solid ${C.border}` }}><div style={{ width: "70%", height: "100%", background: C.amber, borderRadius: 3 }} /></div><Tag label={cr.tempLabel} variant="amber" small /></div></CardPad></Card></div>
          <Card><CardPad style={{ paddingBottom: 4 }}><SectionTitle>近期触达记录</SectionTitle>{cr.contacts.map((contact, index) => <Row key={`${contact.date}-${contact.type}`} last={index === cr.contacts.length - 1}><span style={{ fontSize: 12, color: C.text2, minWidth: 58 }}>{contact.date}</span><Tag label={contact.channel} variant="neutral" small /><span style={{ fontSize: 13, color: C.text0, flex: 1 }}>{contact.type}</span><StatusPill label={contact.result === "positive" ? "✓ 正向反馈" : contact.result} variant={contact.result === "positive" ? "green" : "neutral"} /></Row>)}</CardPad></Card>
          <div style={{ fontSize: 11, fontWeight: 600, color: C.text2, letterSpacing: 0.8, textTransform: "uppercase" }}>近期背景</div>
          <Card><CardPad><SectionTitle>最新相关事件</SectionTitle><div style={{ borderLeft: `3px solid ${C.blue}`, paddingLeft: 12 }}><div style={{ fontSize: 11, color: C.text2, marginBottom: 4 }}>{customer.events[0].id} · {customer.events[0].typeLabel}</div><div style={{ fontSize: 13, color: C.text0, lineHeight: 1.65 }}>{customer.events[0].summary}</div></div></CardPad></Card>
          <Card><CardPad><SectionTitle>最新状态版本</SectionTitle><div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}><span style={{ fontSize: 14, fontWeight: 700, color: C.text0 }}>{customer.stateVersions[0].version}</span><Tag label="重要更新" variant="amber" small /></div><div style={{ fontSize: 12, color: C.text2, marginBottom: 4 }}>变更内容：{customer.stateVersions[0].changed.join("、")}</div><div style={{ fontSize: 12, color: C.text2 }}>触发原因：{customer.stateVersions[0].trigger}</div></CardPad></Card>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: C.text2, letterSpacing: 0.8, textTransform: "uppercase" }}>建议触达方案</div>
          <Card style={{ borderColor: C.blueBorder }}><CardPad><SectionTitle>触达目标</SectionTitle><div style={{ fontSize: 14, color: C.text0, lineHeight: 1.7, background: C.surfaceAlt, padding: "10px 12px", borderRadius: 7, marginBottom: 12 }}>{ro.goal}</div><Row><span style={{ fontSize: 11.5, color: C.text2, minWidth: 72 }}>话术风格</span><span style={{ fontSize: 13, color: C.text0 }}>{ro.style}</span></Row><Row last><span style={{ fontSize: 11.5, color: C.text2, minWidth: 72 }}>时间窗口</span><span style={{ fontSize: 13, color: C.amber, fontWeight: 500 }}>{ro.window}</span></Row></CardPad></Card>
          <Card style={{ borderColor: C.amberBorder }}><CardPad><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}><SectionTitle>审核状态</SectionTitle><Tag label="需要审核" variant="amber" small /></div><div style={{ fontSize: 13, color: C.text0 }}>{ro.review}</div></CardPad></Card>
          <AgentBlock text={ro.script} label="客户助手 · 话术草稿" />
          <Card><CardPad><SectionTitle>置信度与风险</SectionTitle><ConfidenceBar value={customer.confidence} /><div style={{ marginTop: 12, background: C.surfaceAlt, borderRadius: 6, padding: "9px 12px", fontSize: 12, color: C.text1, lineHeight: 1.65 }}>配偶决策权重未知，置信度维持 72%。本次外呼如能推动配偶参与体验，置信度预计可升至 82%。</div></CardPad></Card>
          <Card><CardPad style={{ paddingBottom: 8 }}><SectionTitle>待解问题</SectionTitle>{customer.unresolvedQuestions.map((question, index) => <Row key={question} last={index === customer.unresolvedQuestions.length - 1}><span style={{ color: C.red, fontWeight: 700 }}>?</span><span style={{ fontSize: 13, color: C.text0 }}>{question}</span></Row>)}</CardPad></Card>
          <Card><CardPad><SectionTitle>允许原因与受限原因</SectionTitle><div style={{ marginBottom: 10 }}><div style={{ fontSize: 10.5, fontWeight: 600, color: C.green, marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.5 }}>允许原因</div><div style={{ fontSize: 13, color: C.text1, lineHeight: 1.65 }}>售后资料属于已授权信息范围；家庭体验邀约通过主联系人刘浩转达，不直接触达配偶。</div></div><div><div style={{ fontSize: 10.5, fontWeight: 600, color: C.red, marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.5 }}>受限原因</div><div style={{ fontSize: 13, color: C.text1, lineHeight: 1.65 }}>直接联系配偶违反数据授权规则；承诺折扣超出客服角色权限范围。</div></div></CardPad></Card>
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><PrimaryBtn style={{ flex: 1 }}>记录触达</PrimaryBtn><DangerBtn>升级处理</DangerBtn></div>
        </div>
      </div>
    </div>
  );
}
