export const C = {
  bg: "#F6F8FB",
  surface: "#FFFFFF",
  surfaceAlt: "#F8FAFC",
  border: "#E6EAF0",
  borderMd: "#D7DEE8",
  text0: "#1F2937",
  text1: "#4B5563",
  text2: "#8B96A8",
  text3: "#BEC6D2",
  blue: "#4F6EF7",
  blueLight: "#F3F6FF",
  blueBorder: "#D7DFFF",
  green: "#5B9A74",
  greenLight: "#F4FAF6",
  greenBorder: "#D9EBDC",
  amber: "#BE8A36",
  amberLight: "#FCF8EF",
  amberBorder: "#EEDDB9",
  red: "#C86D67",
  redLight: "#FEF7F6",
  redBorder: "#F0D7D4",
  brick: "#4F6EF7",
  mono: "'JetBrains Mono', 'IBM Plex Mono', monospace",
  sans: "'Inter', 'DM Sans', system-ui, sans-serif",
} as const;
